### ISSUE TITLE
Using time as iterator may cause a transfer failed

### ISSUE THREAD

**Issue by garveen** [MixinNetwork/ocean.one#2]
https://github.com/MixinMessenger/ocean.one/blob/fda98e8f19a7366c25d3f8337c816ea849fae75c/mixin.go#L207
If there are multiple servers running this code, they may have different time;
If a server use NTP to correct its time, the time may go back a few seconds.
According to https://developers.mixin.one/api#documentationencrypted_pin
the iterator must be bigger than the previous

**Comment by cedricfung** [comment]
This service is a single queue now.

**Comment by garveen** [comment]
even it is single queue, the machine time is not single direction; it may turn back a few seconds when using internet time

**Comment by cedricfung** [comment]
Yes, some seconds failure is acceptable, there are retry logic in the queue.

May need to manage a iterator in some persistent layer, but it may be a bit complicated
